# Generated by Django 4.2.1 on 2024-02-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smvs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='name',
            new_name='position',
        ),
    ]
