# Generated by Django 4.2.1 on 2024-02-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smvs', '0002_rename_name_election_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='smvs/files/profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='election',
            name='candidates',
            field=models.ManyToManyField(related_name='elections', to='smvs.candidate'),
        ),
    ]
