# Generated by Django 4.2.1 on 2024-02-25 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smvs', '0004_remove_candidate_election_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
